[tool.poetry]
name = "demo"
version = "0.1.0"
description = "A minimal demo project with Poetry"
authors = ["Your Name <you@demo.com>"]

[tool.poetry.dependencies]
python = ">=3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
